Develop
eugene982/yp-gophkeeper pull request #1
Opened 2023-10-24 17:09 UTC by eugene982

2023-10-27 18:11 UTC, arttet requested changes

2023-10-27 18:11 UTC, arttet commented on proto/v1/gophkeeper.proto
> +    repeated string names = 1;  // массив наименований
Why not bytes?

2023-10-27 18:11 UTC, arttet commented on proto/v1/gophkeeper.proto
> +    string name = 1[(buf.validate.field).string.min_len = 1];
max_len = ?

2023-10-27 18:11 UTC, arttet commented on proto/v1/gophkeeper.proto
> +    bytes  bin   = 2[(buf.validate.field).bytes.min_len = 1, (buf.validate.field).bytes.max_len = 5000000];
We are not allowed to do it. We should use streams.
`.bytes.max_len = 5000000`

2023-11-05 13:42 UTC, eugene982 commented on internal/application/application.go
> +type Application struct {
Не понял про какую строчку, импорт или структура?

2023-11-05 13:42 UTC, eugene982 commented on buf/validate/expression.proto
> +// Copyright 2023 Buf Technologies, Inc.
моя электронка блокируется на сайте, работают только локальные файлы

2023-11-10 21:47 UTC, merged